### PR TITLE
Patch: Fixing Comparison component render warning.

### PR DESCRIPTION
**Pull request by zliuwd**
## Description

There are couple warning shown when Comparison components were rendered.
screen shot 2019-03-04 at 1 18 12 pm

The reason is used empty `<div/>` as child of LoadingBoundary in ClientAssessmentStatistics, so got some refactoring and resolved it.

## Tests

- [ ] I used TDD to develop the feature
- [x] I have included unit tests
- [ ] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I ran all my tests locally which were green.
- [x] My code adds no new issues to Code Climate
- [x] I ran all the linters for the project.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build (or bring donuts if I leave things broken), to check linters, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by zliuwd** [comment]
retest it please

**Comment by wmitchell-cambria** [comment]
I have mixed feelings about both approaches.

The current approach in this PR adds a prop to a couple components that don't feel like they really need it. Why render a Comparison component with no comparison? Why does the AssessmentHistory need knowledge of a comparison at all? (mostly a naming issue)

Denys's proposed approach is cleaner code, but it will cause the loading boundaries to remount, leading to more data fetching. If we want the data to refresh every time you toggle and avoid fetching the comparison when the page loads, this is good...but I think we should be conscious about those tradeoffs rather than having it as a side effect of these warnings.

If I recall, the `<div />` within these loading boundaries was at one point a `Fragment` instead. Did that run into some issue? Maybe the real answer is that the child within the loading boundary should be `isComparisonShown ? <AssessmentComparison /> : null`, and the LoadingBoundary should be set up to handle a `null` child. (Right now, it calls `React.cloneElement` unconditionally, which probably crashes on null.)

**Comment by denys-davydov** [comment]
@wmitchell-cambria Agree about redundant remounting, it is not the best solution. If we change `<div />` with `null` it will fail. But `<Fragment />` instead of `<div />` works great. I think It is the easiest solution.

**Comment by zliuwd** [comment]
### Firstly, thanks for the review from everyone.
#### -For Denys,
The code you provide is very similar as my first version, of course much prettier than mine. That version has an issue: "the page will be reload again" every time when we switch back to history. Then the user experience is not smooth. After talked with Leonid we decide to find a way to make sure the data only load one time for both component. Additionally, I am also not feeling comfortable to create only one boundary for both of them with three fetching at same time. Particularly if we do so, history and comparison's big boundary will lose its reusability. So we wrote the code like that, let them fetch data separately in a same container

**Comment by zliuwd** [comment]
Ok, let we switch back to fragment again.

**Pull request closed without merging**
