### PR TITLE
Update Rails for security patches

### PR DESCRIPTION
**Pull request by wmitchell-cambria**
## JIRA

No story, flagged by GitHub

## Description

This update is in response to the following security vuln patches:
https://weblog.rubyonrails.org/2018/11/27/Rails-4-2-5-0-5-1-5-2-have-been-released/

## Tests

- [ ] I used TDD to develop the feature
- [ ] I have included unit tests
- [ ] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I ran all my tests locally which were green.
- [ ] My code adds no new issues to Code Climate
- [ ] I ran all the linters for the project.
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build (or bring donuts if I leave things broken), to check linters, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by denys-davydov** [comment]
Shouldn't we update the base docker image *cwds/ruby*?

**Comment by wmitchell-cambria** [comment]
Good catch. Let me check with @ratneshraval, but I think we should definitely update the base image as well.

**Comment by wmitchell-cambria** [comment]
Chatted with @ratneshraval. We should follow up with a patch to the base image as well. As long as the app-specific Rails version is patched, we will be secure. Build times will be a little slower until we update the base image to match, though, since it has to install the second version.

**Comment by LeonidMarushevskyi** [comment]
@wmitchell-cambria will rebuild base CANS image to accommodate this changes. So build time will not be affected.

**Pull request merged**
