### PR TITLE
CANS-946 - Use Component Library / Design System layout

### PR DESCRIPTION
**Pull request by wmitchell-cambria**
## JIRA

Partial for [CANS-946 - Replace React Wood Duck headers with Design System headers from Component Library](https://osi-cwds.atlassian.net/browse/CANS-946)

## Description

This switches our page layouts over to the component library / design system components. It does not remove the React Wood Duck dependency yet. (That is next and will likely involve many style fixes.) This PR also removes the feature flag for the new layout, since it turns them on everywhere.

## Tests

- [ ] I used TDD to develop the feature
- [ ] I have included unit tests
- [ ] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

I ran existing tests and manually tested, but for the most part this PR was just ripping out code.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I ran all my tests locally which were green.
- [x] My code adds no new issues to Code Climate
- [x] I ran all the linters for the project.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build (or bring donuts if I leave things broken), to check linters, use best practices, to leave the code in better shape than I found it, and to have a good day.

I need to run regression tests on the PR build. My local tests are seeing a few failures on master as well as my PR branch, so my local results are unreliable at the moment. I'll request reviews once I know they are passing.

### CODE REVIEW

**Comment by wmitchell-cambria** [comment]
This may be a slight overuse of the 'major' label, but I am going for it. :-D

**Comment by zliuwd** [comment]
Firstly, sorry for didn't review your last big PR on time.
Overall great job, particularly the changing for breadcrumb making it with more "Fault tolerance". Down below is something I found, they are small things but I think still good to know.

#### I found some thing "strange" when run this branch locally.
- a. Header font is very big, breadcrumb font also big, and CWDS top small header is fixed now, are these what we expect?
- b.Randomly get userId prop type warning (mostly happened when access an existed assessment or nav to a client profile)
screen shot 2019-02-12 at 11 53 30 pm

- c.Randomly get isSubmitWarningShown prop type warning  (mostly happened when click complete button and click agree button)
screen shot 2019-02-12 at 11 54 24 pm

- d. Item and domain level auto scroll is impacted by this new layout, for now it will scroll up a bit more, domain looks still ok, but item header attached the bottom line of the CANS header. 

#### suggestion
1. For b and c, I think there are some racing between the data fetching and rendering, maybe this issue already existed before this change, but by the change we set some props as required then this issue is revealed.
2. For d, we should adjust "tuner" in AssessmentAutoscroll to get a better result.

**Comment by wmitchell-cambria** [comment]
Thanks for the reviews, all! @zliuwd - I'm going to look into those warnings before merging, just to make sure there's no regression. Good catches!

**Comment by wmitchell-cambria** [comment]
After some investigations, double-checking:

* A) - Yes, these style changes are intentional, based on the Design System headers. Dashboard is a good example in action, and to see breadcrumb styles I compared it to the [Guide Site](https://cws-cares.netlify.com/components/alert)
* B/C) - Looks like these are actually happening on master as well. The userId in question is a staffId, to help generate the right links to the assessments. When you view an assessment history on a non-staff URL, it was null. I will patch it to be optional. The warning modal issues seem related to the AssessmentContainer refactor. I'll patch those in a separate PR.
* C) - Good catch. I've adjusted the page header heights accordingly. I'll have to adjust these again soon, as I need to circle back with DesignOps about the alerts at the top of the page. (The component library does not currently have a sticky slot for them.)

**Pull request merged**
