### PR TITLE
Fix jenkins file to use docker credentials for docker-compose invocation

### PR DESCRIPTION
**Pull request by denys-davydov**
## Description
Fix jenkins file to use docker credentials for docker-compose invocation

### CODE REVIEW

**Comment by edgibbs** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Pull request merged**
