### PR TITLE
CANS-927 Breadcrumb link is allowing the user to access deleted assessment bug fixing up

### PR DESCRIPTION
**Pull request by zliuwd**
## JIRA
https://osi-cwds.atlassian.net/browse/CANS-927
## Description

Assessment Form breadcrumb will not show in any work flow which navigate to a ChangeLog of deleted assessment.
## Tests

- [x] I used TDD to develop the feature
- [x] I have included unit tests
- [ ] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I ran all my tests locally which were green.
- [x] My code adds no new issues to Code Climate
- [x] I ran all the linters for the project.
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build (or bring donuts if I leave things broken), to check linters, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by zliuwd** [comment]
retest this please

**Comment by zliuwd** [comment]
01/08 8:34pm - java.nio.file.FileSystemException: /opt/jenkins/workspace/cans-pr-build: No space left on device
So reviewers please go ahead to review, thank you.

**Comment by LeonidMarushevskyi** [comment]
retest this please

**Comment by LeonidMarushevskyi** [comment]
retest this please

**Pull request merged**
